# Generated by Django 2.0.5 on 2020-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='link',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
