# Generated by Django 2.0.5 on 2019-08-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0030_auto_20190805_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switching_fees', to='profiles.Customer')),
            ],
            options={
                'verbose_name': 'Switching Fee',
                'verbose_name_plural': 'Switching Fees',
            },
        ),
    ]
