# Generated by Django 2.0.5 on 2019-08-20 07:10

import profit_pulse.core.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('switching_fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('imported', 'imported'), ('parse_error', 'parse_error')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('report_url', models.URLField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path)),
            ],
            options={
                'verbose_name': 'Switching Fee Report',
                'verbose_name_plural': 'Switching Fee Reports',
            },
        ),
        migrations.RenameField(
            model_name='switchingfee',
            old_name='date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='switchingfee',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='switchingfee',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='switchingfee',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='switching_fees.SwitchingReport'),
        ),
    ]
