# Generated by Django 2.0.5 on 2018-05-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('dispense', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensehistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_histories', to='profiles.Customer'),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_histories', to='profiles.Physician'),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_histories', to='products.Product'),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='dispense.DispenseReport'),
        ),
    ]
