# Generated by Django 2.0.5 on 2018-06-28 08:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0002_auto_20180507_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensehistory',
            name='trans_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='written_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
