# Generated by Django 2.0.5 on 2019-01-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0003_auto_20180628_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensehistory',
            name='extra',
            field=models.TextField(blank=True),
        ),
    ]
