# Generated by Django 2.0.5 on 2019-11-29 06:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_customer_professional_liability_insurance'),
        ('dispense', '0005_dispensehistory_rf_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('billing_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('switching_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='profiles.Customer')),
            ],
        ),
    ]
