# Generated by Django 2.0.5 on 2020-03-18 14:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_historicalcustomer'),
        ('products', '0006_auto_20191015_0401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispense', '0007_auto_20191202_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDispenseHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('trans_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('insurance_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('rx_number', models.CharField(max_length=128)),
                ('rf_number', models.CharField(max_length=128)),
                ('order_date', models.DateTimeField()),
                ('written_date', models.DateTimeField(blank=True, null=True)),
                ('extra', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.Customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('physician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.Physician')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.Product')),
                ('report', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispense.DispenseReport')),
            ],
            options={
                'verbose_name': 'historical Dispense History',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
