# Generated by Django 2.0.5 on 2018-05-22 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('profiles', '0002_auto_20180509_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('zip_code', models.CharField(blank=True, max_length=40)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="+1-xxx-xxx-xxxx (int'l code required)", max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('portal_access', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
    ]
