# Generated by Django 2.0.5 on 2018-05-22 07:30

from django.db import migrations


def sync_superusers_with_managers(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Manager = apps.get_model('profiles', 'Manager')
    for user in User.objects.filter(is_superuser=True):
        if not Manager.objects.filter(user=user).exists():
            Manager.objects.create(
                user=user,
                portal_access=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_manager'),
    ]

    operations = [
        migrations.RunPython(sync_superusers_with_managers),
    ]
