# Generated by Django 2.0.5 on 2018-05-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180522_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
