# Generated by Django 2.0.5 on 2018-06-26 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180528_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='commissions_owed',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='overhead',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='manager',
            name='commissions_owed',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5),
        ),
        migrations.AddField(
            model_name='manager',
            name='overhead',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='commissions_owed',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='overhead',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
