# Generated by Django 2.0.5 on 2018-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180626_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='physician',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
