# Generated by Django 2.0.5 on 2018-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180628_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='physician',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
