# Generated by Django 2.0.5 on 2018-06-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180628_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='name',
        ),
    ]
