# Generated by Django 2.0.5 on 2018-07-11 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_physician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='num_locations',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)], verbose_name='number of locations'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='num_physicians',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)], verbose_name='number of physicians'),
        ),
    ]
