# Generated by Django 2.0.5 on 2018-11-02 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180711_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('495'), max_digits=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='switching_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_fee_dollar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_fee_percentage',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
    ]
