# Generated by Django 2.0.5 on 2018-11-06 22:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20181106_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='enrollment_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_fee_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
