# Generated by Django 2.0.5 on 2018-11-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20181106_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physicians', to='profiles.Customer'),
        ),
    ]
