# Generated by Django 2.0.5 on 2018-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20181204_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credentialed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
