# Generated by Django 2.0.5 on 2019-01-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20181212_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='profiles.Customer'),
        ),
    ]
