# Generated by Django 2.0.5 on 2019-02-21 01:57

import profit_pulse.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_customer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='articles_of_incorporation',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='dea_license',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='facility_liability_insurance',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='facility_medicare',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='facility_npi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='irs_tax_documentation',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='ncpdp_number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='npi_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='practice_w9',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_license_verification',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_medical_license',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
    ]
