# Generated by Django 2.0.5 on 2019-02-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20190220_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credentialing_stage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
