# Generated by Django 2.0.5 on 2019-03-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190303_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization_npi',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
