# Generated by Django 2.0.5 on 2019-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_customer_organization_npi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='customer',
        ),
        migrations.AddField(
            model_name='physician',
            name='customers',
            field=models.ManyToManyField(related_name='physicians', to='profiles.Customer'),
        ),
    ]
