# Generated by Django 2.0.5 on 2019-04-20 08:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20190312_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_goal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='manager',
            name='company_goal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='company_goal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
