# Generated by Django 2.0.5 on 2019-05-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20190420_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='credentialing_only',
            field=models.BooleanField(default=False),
        ),
    ]
