# Generated by Django 2.0.5 on 2019-05-20 07:22

import profit_pulse.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_manager_credentialing_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='articles_of_incorporation',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='caremark',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dea_license',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='express_scripts',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='facility_liability_insurance',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='facility_medicare_and_medicaid_member_id',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='facility_npi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='humana_optum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='irs_tax_documentation',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='npi_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='practice_w9',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='professional_liability_policy',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='psao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_license_verification',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_medical_license',
            field=models.FileField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
    ]
