# Generated by Django 2.0.5 on 2019-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20190520_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='humana_optum',
            new_name='humana',
        ),
        migrations.AddField(
            model_name='customer',
            name='optum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
