# Generated by Django 2.0.5 on 2019-12-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_customer_professional_liability_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner_1_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_2_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_3_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_4_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_5_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_6_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
