# Generated by Django 2.0.5 on 2019-12-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20191205_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='percent_340b',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='percent_compounds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='percent_diabetic_supplies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='percent_dme_otc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='percent_medicaid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='percent_medicare',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='percent_workers_comp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='yn_e_prescribe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='yn_public_transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='yn_walking_distance',
            field=models.BooleanField(default=False),
        ),
    ]
