# Generated by Django 2.0.5 on 2020-01-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20191208_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credentialing_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'credentialing_only': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='profiles.Manager'),
        ),
    ]
