# Generated by Django 2.0.5 on 2020-01-09 15:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_customer_credentialing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owners',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
