# Generated by Django 2.0.5 on 2020-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_customer_credentialing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='yn_medicaid_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='yn_medicare_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='yn_percent_medicaid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='yn_percent_medicare',
            field=models.TextField(blank=True),
        ),
    ]
