# Generated by Django 2.0.5 on 2020-01-09 15:01

from django.db import migrations


def combine_owners(apps, schema_editor):
    Customer = apps.get_model('profiles', 'Customer')
    owners = []
    for customer in Customer.objects.all():
        try:
            if (
                customer.owner_1_name or
                customer.owner_1_email or
                customer.owner_1_percent_owned or
                customer.owner_1_dob or
                customer.owner_1_social_security_number or
                customer.owner_1_address_line_1 or
                customer.owner_1_city or
                customer.owner_1_state or
                customer.owner_1_postal_code
            ):
                owners.append({
                    'name': customer.owner_1_name,
                    'email': customer.owner_1_email,
                    'percent_owned': customer.owner_1_percent_owned,
                    'dob': customer.owner_1_dob,
                    'social_security_number': customer.owner_1_social_security_number,
                    'address_line_1': customer.owner_1_address_line_1,
                    'city': customer.owner_1_city,
                    'state': customer.owner_1_state,
                    'postal_code': customer.owner_1_postal_code,
                })
            if (
                customer.owner_2_name or
                customer.owner_2_email or
                customer.owner_2_percent_owned or
                customer.owner_2_dob or
                customer.owner_2_social_security_number or
                customer.owner_2_address_line_1 or
                customer.owner_2_city or
                customer.owner_2_state or
                customer.owner_2_postal_code
            ):
                owners.append({
                    'name': customer.owner_2_name,
                    'email': customer.owner_2_email,
                    'percent_owned': customer.owner_2_percent_owned,
                    'dob': customer.owner_2_dob,
                    'social_security_number': customer.owner_2_social_security_number,
                    'address_line_1': customer.owner_2_address_line_1,
                    'city': customer.owner_2_city,
                    'state': customer.owner_2_state,
                    'postal_code': customer.owner_2_postal_code,
                })
            if (
                customer.owner_3_name or
                customer.owner_3_email or
                customer.owner_3_percent_owned or
                customer.owner_3_dob or
                customer.owner_3_social_security_number or
                customer.owner_3_address_line_1 or
                customer.owner_3_city or
                customer.owner_3_state or
                customer.owner_3_postal_code
            ):
                owners.append({
                    'name': customer.owner_3_name,
                    'email': customer.owner_3_email,
                    'percent_owned': customer.owner_3_percent_owned,
                    'dob': customer.owner_3_dob,
                    'social_security_number': customer.owner_3_social_security_number,
                    'address_line_1': customer.owner_3_address_line_1,
                    'city': customer.owner_3_city,
                    'state': customer.owner_3_state,
                    'postal_code': customer.owner_3_postal_code,
                })
            if (
                customer.owner_4_name or
                customer.owner_4_email or
                customer.owner_4_percent_owned or
                customer.owner_4_dob or
                customer.owner_4_social_security_number or
                customer.owner_4_address_line_1 or
                customer.owner_4_city or
                customer.owner_4_state or
                customer.owner_4_postal_code
            ):
                owners.append({
                    'name': customer.owner_4_name,
                    'email': customer.owner_4_email,
                    'percent_owned': customer.owner_4_percent_owned,
                    'dob': customer.owner_4_dob,
                    'social_security_number': customer.owner_4_social_security_number,
                    'address_line_1': customer.owner_4_address_line_1,
                    'city': customer.owner_4_city,
                    'state': customer.owner_4_state,
                    'postal_code': customer.owner_4_postal_code,
                })
            if (
                customer.owner_5_name or
                customer.owner_5_email or
                customer.owner_5_percent_owned or
                customer.owner_5_dob or
                customer.owner_5_social_security_number or
                customer.owner_5_address_line_1 or
                customer.owner_5_city or
                customer.owner_5_state or
                customer.owner_5_postal_code
            ):
                owners.append({
                    'name': customer.owner_5_name,
                    'email': customer.owner_5_email,
                    'percent_owned': customer.owner_5_percent_owned,
                    'dob': customer.owner_5_dob,
                    'social_security_number': customer.owner_5_social_security_number,
                    'address_line_1': customer.owner_5_address_line_1,
                    'city': customer.owner_5_city,
                    'state': customer.owner_5_state,
                    'postal_code': customer.owner_5_postal_code,
                })
            if (
                customer.owner_6_name or
                customer.owner_6_email or
                customer.owner_6_percent_owned or
                customer.owner_6_dob or
                customer.owner_6_social_security_number or
                customer.owner_6_address_line_1 or
                customer.owner_6_city or
                customer.owner_6_state or
                customer.owner_6_postal_code
            ):
                owners.append({
                    'name': customer.owner_6_name,
                    'email': customer.owner_6_email,
                    'percent_owned': customer.owner_6_percent_owned,
                    'dob': customer.owner_6_dob,
                    'social_security_number': customer.owner_6_social_security_number,
                    'address_line_1': customer.owner_6_address_line_1,
                    'city': customer.owner_6_city,
                    'state': customer.owner_6_state,
                    'postal_code': customer.owner_6_postal_code,
                })
            customer.owners = owners
            customer.save()
        except Exception:
            print('Cannot change data {}'. format(customer.pk))
            raise


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_customer_owners'),
    ]

    operations = [
        migrations.RunPython(combine_owners)
    ]
