# Generated by Django 2.0.5 on 2020-01-09 14:26

import profit_pulse.core.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20200108_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('medical_clinic_license', 'medical_clinic_license'), ('pic_dea_license', 'pic_dea_license'), ('federal_tax_id', 'federal_tax_id'), ('business_liability_insurance', 'business_liability_insurance'), ('owner_pic_drivers_license', 'owner_pic_drivers_license'), ('articles_of_incorporation', 'articles_of_incorporation'), ('professional_liability_insurance', 'professional_liability_insurance')], max_length=128)),
                ('document', models.FileField(upload_to=profit_pulse.core.mixins.get_upload_path)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='profiles.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
