# Generated by Django 2.0.5 on 2020-01-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20200110_0006'),
        ('profiles', '0037_auto_20200109_1001'),
    ]

    operations = [
    ]
