# Generated by Django 2.0.5 on 2020-01-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20200114_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='caremark_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='express_scripts_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='humana_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ncpdp_number_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='optum_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization_npi_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='psao_color',
            field=models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('orange', 'ORANGE')], max_length=128, null=True),
        ),
    ]
