# Generated by Django 2.0.5 on 2020-01-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20200116_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='caremark_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='express_scripts_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='humana_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ncpdp_number_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='optum_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization_npi_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='psao_note',
            field=models.TextField(null=True),
        ),
    ]
