# Generated by Django 2.0.5 on 2020-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_auto_20200128_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='documents_received_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
