# Generated by Django 2.0.5 on 2020-01-29 04:53

import json
import django.contrib.postgres.fields.jsonb
from django.db import migrations




def transform_note_fields(apps, schema_editor):
    Customer = apps.get_model('profiles', 'Customer')
    for customer in Customer.objects.all():
        customer.caremark_note = json.dumps([{'text': customer.caremark_note}]) if customer.caremark_note else '[]'
        customer.express_scripts_note = json.dumps([{'text': customer.express_scripts_note}]) if customer.express_scripts_note else '[]'
        customer.humana_note = json.dumps([{'text': customer.humana_note}]) if customer.humana_note else '[]'
        customer.ncpdp_number_note = json.dumps([{'text': customer.ncpdp_number_note}]) if customer.ncpdp_number_note else '[]'
        customer.optum_note = json.dumps([{'text': customer.optum_note}]) if customer.optum_note else '[]'
        customer.organization_npi_note = json.dumps([{'text': customer.organization_npi_note}]) if customer.organization_npi_note else '[]'
        customer.psao_note = json.dumps([{'text': customer.psao_note}]) if customer.psao_note else '[]'
        customer.software_and_supplies_note = json.dumps([{'text': customer.software_and_supplies_note}]) if customer.software_and_supplies_note else '[]'
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180628_0902'),
    ]

    operations = [
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_customer_documents_received_note'),
    ]

    operations = [
        migrations.RunPython(transform_note_fields),
        migrations.RemoveField(
            model_name='customer',
            name='documents_received_note',
        ),
        migrations.AlterField(
            model_name='customer',
            name='caremark_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='express_scripts_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='humana_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ncpdp_number_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='optum_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization_npi_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='psao_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='software_and_supplies_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
