# Generated by Django 2.0.5 on 2020-01-31 15:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_auto_20200128_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='documents_received_note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
