# Generated by Django 2.0.5 on 2020-02-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_customer_documents_received_note'),
    ]

    operations = [
        migrations.RenameField('Customer', 'ppa_street_1', 'ppa_suite_number'),
    ]
