# Generated by Django 2.0.5 on 2020-02-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_auto_20200205_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ppa_street_2',
        ),
    ]
