# Generated by Django 2.0.5 on 2020-02-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_remove_customer_ppa_street_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='priority_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
