# Generated by Django 2.0.5 on 2020-02-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_customer_priority_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='priority_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
