# Generated by Django 2.0.5 on 2020-02-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20200226_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='priority_date',
        ),
    ]
