# Generated by Django 2.0.5 on 2020-03-05 05:42

import profit_pulse.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20200226_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='document_preview',
            field=models.ImageField(blank=True, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
    ]
