# Generated by Django 2.0.5 on 2020-04-03 10:43

import profit_pulse.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_historicalcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='document',
            field=models.FileField(max_length=255, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
    ]
