# Generated by Django 2.0.5 on 2020-04-03 14:13

import profit_pulse.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_auto_20200403_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='document_preview',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=profit_pulse.core.mixins.get_upload_path),
        ),
    ]
