# Generated by Django 2.0.5 on 2020-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0061_auto_20200403_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='show_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='show_fees',
            field=models.BooleanField(default=False),
        ),
    ]
