# Generated by Django 2.0.5 on 2019-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190828_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_3_years_average_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_3_years_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
