# Generated by Django 2.0.5 on 2019-12-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191218_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpasswordtoken',
            old_name='expiration_date',
            new_name='expiration_datetime',
        ),
    ]
