# Generated by Django 2.0.5 on 2019-12-18 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191218_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
