# Generated by Django 2.0.5 on 2020-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191218_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_local_auth',
            field=models.BooleanField(default=False),
        ),
    ]
